CREATE TABLE t_sugar_project(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '索引值' ,
    product_type VARCHAR(32)    COMMENT '产品类型' ,
    platform_name VARCHAR(128)    COMMENT '平台名称' ,
    demand_review VARCHAR(1024)    COMMENT '5、需求评审' ,
    demand_confirm VARCHAR(1024)    COMMENT '6、需求单确认' ,
    demand_check VARCHAR(1024)    COMMENT '7、验收' ,
    technology_selection TEXT    COMMENT '1、技术选型' ,
    environment_deployment VARCHAR(1024)    COMMENT '2、环境部署' ,
    framework_design TEXT    COMMENT '3、框架设计' ,
    develop_progress_10 VARCHAR(1024)    COMMENT '4、开发进度10%' ,
    develop_progress_25 VARCHAR(1024)    COMMENT '5、开发进度25%' ,
    develop_progress_50 VARCHAR(1024)    COMMENT '6、开发进度50%' ,
    develop_progress_75 VARCHAR(1024)    COMMENT '7、开发进度75%' ,
    develop_progress_100 VARCHAR(1024)    COMMENT '8、开发进度100%' ,
    inside_test TEXT    COMMENT '9、内部测试优化' ,
    customer_test TEXT    COMMENT '10、客户测试优化' ,
    implement_deliver VARCHAR(1024)    COMMENT '11、实施交付' ,
    check_deliver TEXT    COMMENT '12、验收' ,
    status VARCHAR(32)    COMMENT '状态（01有效 99 失效）' ,
    CREATED_STAFF VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_STAFF VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '项目信息 ';